export enum StorageEventType {
    BEFORE_ADD_BUCKET = 'BEFORE_ADD_BUCKET',
    BUCKET_ADDED = 'BUCKET_ADDED',
    BUCKET_ADD_ERROR = 'BUCKET_ADD_ERROR',
    BEFORE_REMOVE_BUCKET = 'BEFORE_REMOVE_BUCKET',
    BUCKET_REMOVED = 'BUCKET_REMOVED',
    BUCKET_REMOVE_ERROR = 'BUCKET_REMOVED',
    BEFORE_DESTROY_BUCKET = 'BEFORE_DESTROY_BUCKET',
    BUCKET_DESTROYED = 'BUCKET_DESTROYED',
    BUCKET_DESTROY_ERROR = 'BUCKET_DESTROY_ERROR',
}
